// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/sartoopjj/dnsttui/internal/database"
import "fmt"

func SettingsPage(cfg database.PanelConfig) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Settings</h1><!-- Restart Services + Alert --> <div class=\"mb-6 flex items-center justify-between rounded-lg bg-white p-4 shadow\"><div><h3 class=\"text-sm font-medium text-gray-900\">Restart All Services</h3><p class=\"text-xs text-gray-500\">Restarts DNS tunnel, Shadowsocks, and panel to apply config changes.</p></div><button hx-post=\"settings/restart\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\" hx-confirm=\"Restart all services? Active connections will be dropped.\" class=\"rounded-md bg-yellow-600 px-4 py-2 text-sm font-semibold text-gray-900 shadow-sm hover:bg-yellow-500\">Restart Services</button></div><div id=\"settings-alert\" class=\"mb-4\"></div><div class=\"space-y-8\"><!-- DNS Tunnel Settings --><div class=\"rounded-lg bg-white p-6 shadow\"><h3 class=\"text-lg font-medium text-gray-900 mb-4\">DNS Tunnel (dnstt)</h3><form hx-post=\"settings\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\"><div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2\"><div><label class=\"block text-sm font-medium text-gray-700\">Domain</label> <input type=\"text\" name=\"dnstt_domain\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.DNSTTDomain)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 35, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" placeholder=\"t.example.com\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">UDP Listen Address</label> <input type=\"text\" name=\"dnstt_udp_addr\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.DNSTTUDPAddr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 40, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" placeholder=\":5300\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">MTU</label> <input type=\"number\" name=\"dnstt_mtu\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", cfg.DNSTTMTU))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 45, Col: 84}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" min=\"500\" max=\"4096\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Public Key</label> <input type=\"text\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.DNSTTPubkey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 50, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" readonly class=\"mt-1 block w-full rounded-md bg-gray-100 border-gray-300 shadow-sm sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300 text-gray-500\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500\">Save DNS Tunnel Settings</button></div></form></div><!-- Shadowsocks Settings --><div class=\"rounded-lg bg-white p-6 shadow\"><h3 class=\"text-lg font-medium text-gray-900 mb-4\">Shadowsocks</h3><form hx-post=\"settings\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\"><div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2\"><div><label class=\"block text-sm font-medium text-gray-700\">Listen Address</label> <input type=\"text\" name=\"ss_listen_addr\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.SSListenAddr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 69, Col: 72}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" placeholder=\"127.0.0.1\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Port</label> <input type=\"number\" name=\"ss_port\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", cfg.SSPort))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 74, Col: 80}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" min=\"1\" max=\"65535\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Method</label> <input type=\"text\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.SSMethod)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 79, Col: 46}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" readonly class=\"mt-1 block w-full rounded-md bg-gray-100 border-gray-300 shadow-sm sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300 text-gray-500\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Server Key</label> <input type=\"text\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.SSServerKey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 84, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" readonly class=\"mt-1 block w-full rounded-md bg-gray-100 border-gray-300 shadow-sm sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300 text-xs text-gray-500\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500\">Save Shadowsocks Settings</button></div></form></div><!-- Client Config Defaults --><div class=\"rounded-lg bg-white p-6 shadow\"><h3 class=\"text-lg font-medium text-gray-900 mb-4\">Client Config Defaults</h3><p class=\"text-sm text-gray-500 mb-4\">DNS resolver used in generated client configs. Users must find a working resolver that can reach your authoritative DNS server (e.g. their ISP resolver, or a public resolver not blocked in their region).</p><form hx-post=\"settings\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\"><div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2\"><div><label class=\"block text-sm font-medium text-gray-700\">DNS Resolver Address</label> <input type=\"text\" name=\"dns_resolver_addr\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.DNSResolverAddr)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 104, Col: 78}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" placeholder=\"8.8.8.8\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"><p class=\"mt-1 text-xs text-gray-500\">Default value for new configs. Each user may need a different resolver.</p></div><div><label class=\"block text-sm font-medium text-gray-700\">DNS Resolver Port</label> <input type=\"number\" name=\"dns_resolver_port\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%d", cfg.DNSResolverPort))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 110, Col: 99}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" min=\"1\" max=\"65535\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500\">Save Client Defaults</button></div></form></div><!-- Panel Settings --><div class=\"rounded-lg bg-white p-6 shadow\"><h3 class=\"text-lg font-medium text-gray-900 mb-4\">Panel Settings</h3><form hx-post=\"settings\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\"><div class=\"grid grid-cols-1 gap-4 sm:grid-cols-2\"><div><label class=\"block text-sm font-medium text-gray-700\">Admin Username</label> <input type=\"text\" name=\"admin_user\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.AdminUser)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 129, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Panel Base Path</label> <input type=\"text\" name=\"panel_base_path\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var14 string
			templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.PanelBasePath)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 134, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "\" placeholder=\"/a8f3b2c1\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"><p class=\"mt-1 text-xs text-gray-500\">Random subpath for the panel URL (e.g. /a8f3b2c1). Requires restart.</p></div><div><label class=\"block text-sm font-medium text-gray-700\">Panel Domain (for ACME TLS)</label> <input type=\"text\" name=\"panel_domain\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.PanelDomain)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 140, Col: 69}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var15))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" placeholder=\"panel.example.com\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">ACME Email</label> <input type=\"email\" name=\"acme_email\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.JoinStringErrs(cfg.ACMEEmail)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/panel/components/settings.templ`, Line: 145, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var16))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "\" placeholder=\"you@example.com\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"rounded-md bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500\">Save Panel Settings</button></div></form></div><!-- Change Password --><div class=\"rounded-lg bg-white p-6 shadow\"><h3 class=\"text-lg font-medium text-gray-900 mb-4\">Change Password</h3><form hx-post=\"settings/password\" hx-target=\"#settings-alert\" hx-swap=\"innerHTML\"><div class=\"grid grid-cols-1 gap-4 sm:grid-cols-3\"><div><label class=\"block text-sm font-medium text-gray-700\">Current Password</label> <input type=\"password\" name=\"current_password\" required class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">New Password</label> <input type=\"password\" name=\"new_password\" required minlength=\"6\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Confirm Password</label> <input type=\"password\" name=\"confirm_password\" required minlength=\"6\" class=\"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm py-1.5 px-3 ring-1 ring-inset ring-gray-300\"></div></div><div class=\"mt-4\"><button type=\"submit\" class=\"rounded-md bg-red-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-red-500\">Update Password</button></div></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Settings").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
